name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Add CNAME file for custom domain from environment variable
      - name: Add CNAME file
        run: |
          echo "${{ secrets.CUSTOM_DOMAIN }}" > build/CNAME
        env:
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}

      # Step 6: Upload the build output to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          publish_dir: ./build