name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Add CNAME file for custom domain
      - name: Add CNAME file
        run: echo "${{ secrets.CUSTOM_DOMAIN }}" > build/CNAME

      # Step 6: Debug the build directory
      - name: Debug build directory
        run: ls -la ./build

      # Step 7: Upload build output as an artifact
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./build

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      # Step 8: Download the artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
      
      # Step 8: Debug the downloaded artifact
      - name: Debug downloaded artifact
        run: ls -la

      # Step 9: Extract the artifact
      - name: Extract artifact
        run: mkdir -p ./build && mv build-output/* ./build

      # Step 10: Debug the extracted build directory
      - name: Debug extracted build directory
        run: ls -R ./build

      # Step 11: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1